package shared;


/**
* shared/FrontEndInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Wednesday, November 18, 2020 3:14:18 PM EST
*/

public interface FrontEndInterface extends FrontEndInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndInterface
