package shared;

/**
* shared/FrontEndInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Wednesday, November 18, 2020 3:14:18 PM EST
*/

public final class FrontEndInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public shared.FrontEndInterface value = null;

  public FrontEndInterfaceHolder ()
  {
  }

  public FrontEndInterfaceHolder (shared.FrontEndInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = shared.FrontEndInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    shared.FrontEndInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return shared.FrontEndInterfaceHelper.type ();
  }

}
