package shared.FrontEndInterfacePackage;


/**
* shared/FrontEndInterfacePackage/productsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Wednesday, November 18, 2020 3:14:18 PM EST
*/

public final class productsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public productsHolder ()
  {
  }

  public productsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = shared.FrontEndInterfacePackage.productsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    shared.FrontEndInterfacePackage.productsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return shared.FrontEndInterfacePackage.productsHelper.type ();
  }

}
